### ISSUE TITLE
file corrupted ?

### ISSUE THREAD

**Issue by Hobohumpinslobobabe** [bportaluri/ALA#1]
Hi, 
The library manager tells "CRC doesn't match. File is corrupted"
And even dl the zip file was not easy.

**Comment by bportaluri** [comment]
I have tried to install the library on my Arduino IDE 1.6.2 and it works fine.
Which IDE version are you using?
Can you try one more time?

**Comment by Hobohumpinslobobabe** [comment]
I'm using Arduino 1.6.4
Still the same message.

**Comment by bportaluri** [comment]
Can you try with the new release?
Still have the same problem.
