### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by BNNorman** [bportaluri/ALA#25]
I'm not sure how to feed fixes back as I haven't collaborated on a github project before.

I have forked this project to https://github.com/BNNorman/ALA and I've uploaded a fix to  AlaLed and enhanced both Alaled and AlaLedRgb so that animation sequences can be stopped/started to allow for switching animation sequences.

I don't want to mess anything up on the master here so my question is "Do I just create a pull request from my forked repository?"

Thanks for any help.

**Comment by bportaluri** [comment]
See #24
