### ISSUE TITLE
ALA_STOPSEQ

### ISSUE THREAD

**Issue by BNNorman** [bportaluri/ALA#26]
Bruno,

Thank you for implementing ALA_STOPSEQ in the master. It seems to work ok.

However, I have a couple of comments.

**runAnimation()** 
This returns a boolean but you have placed a simple return with no value at the beginning when testing for ALA_STOPSEQ in both AlaLed and AlaLedRgb . Surely there should be an explicit false returned?  I understand the default return will probably be a zero value int (=false) but isn't that, possibly, compiler dependent? 

**ALA_STOPSEQ**
I'm guessing that if the caller does not call getAnimation() ALA_STOPSEQ will just time out and the animation sequence will just loop again.

**Example**
  // 24 leds driven by pin 11   _<---- this might confuse newbies as you used 10 leds on pin 6 below_
  rgbStrip.initWS2812(10, 6);

Regards
Brian

**Comment by bportaluri** [comment]
Thank you again for the feedback.
I have fixed the small issues you pointed out and committed release 2.3.7
If the called does not call getAnimation() the sequence is stopped. The getAnimation() is used to detect the animation sequence end and trigger some custom code and next animation.
