### ISSUE TITLE
[Solved] Multiple Strips with different led count 

### ISSUE THREAD

**Issue by jrsarath** [bportaluri/ALA#27]
Hi there,
Thanks for the wonderful library, i was wondering if i could drive three or four WS2812 strip with different led counts on every strip, like can i use four different pwm pins on arduino to control those 4 led strips ?
i was looking into multiled sequence but seems like thats not actually suitable 

anything you suggest ?

**Comment by BNNorman** [comment]
The multiled sequence example uses PWM LEDs not WS2812. Follow the SimpleRgbStrip example BUT create three strips like this:-

AlaLedRgb rgbStrip1;
AlaLedRgb rgbStrip2;
AlaLedRgb rgbStrip;3

Then in setup() you init the strips and set the number of leds and pins like this:-

  rgbStrip1.initWS2812(30, 6); // 30 leds on pin 6
  rgbStrip2.initWS2812(30, 7); // using pin 7
  rgbStrip3.initWS2812(30, 8); // using pin 8

You can define your own animation sequences or just add one animation to each strip

  rgbStrip1.setAnimation(ALA_FADECOLORSLOOP, 5000, alaPalRgb);
  rgbStrip2.setAnimation(ALA_SPARKLE, 5000, alaPalRgb);
  rgbStrip3.setAnimation(ALA_FADEINOUT 5000, alaPalRgb);

Then in your loop() do this ..

void loop()
{
  // run the animation
  rgbStrip1.runAnimation();
  rgbStrip2.runAnimation();
  rgbStrip3.runAnimation();
}

BIG RED WARNING: you wil rapidly run out of RAM. Each strip uses an array of num_leds*3 (RGB) bytes - and is double buffered (IIRC - so double it again) so work out your limits. If your strip is , say 144 leds long, each strip would use 864 bytes. The code also need space for variables. A NANO only has 2Kb ram.

If your strip is 144 leds long you can lie to ALA and tell it it is shorter - say 72 - the remaining 72 will not be used. Again IIRC.

Hope that helps.

**Comment by jrsarath** [comment]
Hello @BNNorman  thanks for your kind reponse,
actually i'm even using AlaWeb to control the arduino..
let me explain my situation here..
im trying to build a RGB lighting system for my pc which includes a WS2812 strip along with ws2812 included fan..
so im planing to control the STRIP and the fans separately, the strip has 100 LED and fan has 28 LED, so besically let say one strip is 100LED long another one is 28 led

how do you propose i go with this ?

EDIT : im using a arduino leonardo pro micro

**Comment by jrsarath** [comment]
@BNNorman thank you your concept led me to success, thank you so much senior.
Peace and respect

**Comment by BNNorman** [comment]
Only use rgbStrip1 and rgbStrip2.
RgbStrip1.init(100,pin1);
RgbStrip2.init(28,pin2);
You choose which pins to use as pin1 and pin2

**Comment by jrsarath** [comment]
thats what i did, and whereever i saw rgbStrip1.function in the serial eaxmple file i just copied it with rgstrip2.function

working fine now..  thanks again
