### ISSUE TITLE
Attiny support?

### ISSUE THREAD

**Issue by charmanjoe** [bportaluri/ALA#5]
I'm using an Attiny85 in a simple project to control 6 RGB LEDs.  I'd like to use this library with it, but it doesn't seem to support it.  I'm using the method described here to program the Attiny85 using my Arduino UNO as isp: http://highlowtech.org/?p=1695.  When I try it with the SimpleRgbLed sketch it says: E:\Arduino\libraries\ALA\src\pinouts/chip_includes.h:114:2: error: #error "Unknown Chip!"

**Comment by bportaluri** [comment]
Sorry, no plan to include Attiny85 support.
