### ISSUE TITLE
bug with rgb strip sequence demo on UNO and 150 leds

### ISSUE THREAD

**Issue by sophana** [bportaluri/ALA#8]
Hi

My setup is an arduino uno driving a led strip of 150 ws2812b. (arduino v1.0.5)
It works nice at the begining, but during the demo sequence, something goes wrong, and it looks like some memory corruption occurs because of one of the animations.
Sometime, the number of led changes, sometime, the whole animation speed changes.

I suspect fire, or bubbles animation to cause corruption.
When I remove a these, everything seems to work ok.

**Comment by bportaluri** [comment]
Arduino Uno has well known memory limitations.
Fire and bubbles animations are memory intensive so it is probable that you are having memory corruption when using many leds.
There is no way of avoiding this. I suggest you to reduce the number of leds or use and Arduino Mega.
